on:
  push:
    branches:
      - dev
      - production

    paths:
      - "JSREPORTS/**"


jobs:
  call-prod:
    if: github.ref == 'refs/heads/production'
    # Importing a reusable workflow
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/jsreports.yml
    # Passing secrets account wise 
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-github-role-arn: ${{ secrets.CG_AWS_PROD_ROLE }}

  call-dev:
    if: github.ref == 'refs/heads/dev'
    # Importing a reusable workflow
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    uses: ./.github/workflows/jsreports.yml
    # Passing secrets account wise 
    secrets:
      aws-region: ${{ secrets.AWS_REGION }}
      aws-github-role-arn: ${{ secrets.CG_AWS_DEV_ROLE }}
